[package]
name = "mandelbrot"
version = "0.1.0"
authors = ["Sebastian Dr√∂ge <sebastian@centricular.com>"]
edition = "2018"

[dependencies]
glib = "0.7"
gio = "0.6"
gdk = "0.10"
gtk = "0.6"
cairo-rs = "0.6"
lazy_static = "1.0"
num-complex = "0.2"
rayon = "1.0"
