[package]
name = "mandelbrot"
version = "0.1.0"
authors = ["Sebastian Dr√∂ge <sebastian@centricular.com>"]

[dependencies]
glib = { version = "0.6", features = ["futures"] }
futures-preview = "0.2"
gio = "0.5"
gdk = "0.9"
gtk = "0.5"
cairo-rs = "0.5"
lazy_static = "1.0"
num-complex = "0.2"
rayon = "1.0"
